// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Activité utilisateur classique', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Activité utilisateur classique', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1215, height: 735 })
    await driver.findElement(By.id(":r5:")).sendKeys("test@locamat.fr")
    await driver.findElement(By.id(":r7:")).sendKeys("Test123@")
    await driver.findElement(By.css(".MuiButton-root")).click()
    await driver.findElement(By.css(".material-card:nth-child(1) .MuiPaper-root:nth-child(2) .MuiCardMedia-root")).click()
    await driver.findElement(By.linkText("Home")).click()
    await driver.findElement(By.css(".material-card:nth-child(1) .MuiButtonBase-root")).click()
    await driver.findElement(By.css(".cardHardware:nth-child(1) .imgHardware")).click()
    await driver.findElement(By.linkText("Home")).click()
    {
      const element = await driver.findElement(By.css(".material-card:nth-child(4) .MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".material-card:nth-child(4) .MuiButtonBase-root")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".cardHardware:nth-child(2) .imgHardware")).click()
    {
      const element = await driver.findElement(By.linkText("Home"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("Home")).click()
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(3)")).click()
    {
      const element = await driver.findElement(By.linkText("Home"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id(":rd:")).sendKeys("test@locamat.fr")
    await driver.findElement(By.id(":rf:")).sendKeys("Test123@")
  })
})
