// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Admin create new user', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Admin create new user', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1215, height: 735 })
    await driver.findElement(By.id(":r5:")).sendKeys("admin@locamat.fr")
    await driver.findElement(By.id(":r7:")).sendKeys("Root123@")
    await driver.findElement(By.id(":r5:")).click()
    await driver.findElement(By.id(":r7:")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-root")).click()
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(3)")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-root")).click()
    await driver.findElement(By.id(":r1j:")).click()
    await driver.findElement(By.id(":r1j:")).sendKeys("Test")
    await driver.findElement(By.id(":r1l:")).click()
    await driver.findElement(By.id(":r1l:")).sendKeys("TestName")
    await driver.findElement(By.id(":r1n:")).click()
    await driver.findElement(By.id(":r1n:")).sendKeys("0234567891")
    await driver.findElement(By.id(":r1p:")).click()
    await driver.findElement(By.id(":r1p:")).click()
    await driver.findElement(By.id(":r1p:")).sendKeys("test02@locamat.fr")
    await driver.findElement(By.id(":r1r:")).click()
    await driver.findElement(By.id("root")).click()
    await driver.findElement(By.id(":r1r:")).sendKeys("Test123@")
    await driver.findElement(By.css(".MuiButton-root")).click()
    assert(await driver.switchTo().alert().getText() == "User created successfully")
    await driver.findElement(By.linkText("Home")).click()
    {
      const element = await driver.findElement(By.css(".MuiIconButton-root:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".MuiButtonBase-root:nth-child(3) > .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(3)")).click()
    await driver.findElement(By.id(":rd:")).sendKeys("admin@locamat.fr")
    await driver.findElement(By.id(":rf:")).sendKeys("Root123@")
    await driver.findElement(By.css(".MuiButton-root")).click()
    {
      const element = await driver.findElement(By.css(".material-card:nth-child(2) .MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(3)")).click()
    {
      const element = await driver.findElement(By.css(".MuiTableRow-root:nth-child(3) .MuiButtonBase-root:nth-child(2) > .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiTableRow-root:nth-child(3) .MuiButtonBase-root:nth-child(2) > .MuiSvgIcon-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".MuiDialogActions-root > .MuiButtonBase-root:nth-child(2)")).click()
    await driver.close()
  })
})
