// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Admin on hardware', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Admin on hardware', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1215, height: 735 })
    await driver.findElement(By.id(":r5:")).sendKeys("admin@locamat.fr")
    await driver.findElement(By.id(":r7:")).sendKeys("Root123@")
    await driver.findElement(By.css("form")).click()
    await driver.findElement(By.css(".connexionDiv")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-root")).click()
    {
      const element = await driver.findElement(By.css(".material-card:nth-child(2) .MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(3)")).click()
    await driver.findElement(By.id("mui-p-9561-T-hardware")).click()
    {
      const element = await driver.findElement(By.css(".MuiTableRow-root:nth-child(1) .MuiButtonBase-root:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".MuiTableRow-root:nth-child(1) .MuiButtonBase-root:nth-child(2) > .MuiSvgIcon-root")).click()
    await driver.findElement(By.id(":r1r:")).click()
    await driver.findElement(By.id(":r1r:")).sendKeys("PC2")
    await driver.findElement(By.id(":r1v:")).click()
    await driver.findElement(By.id(":r25:")).click()
    {
      const element = await driver.findElement(By.css(".css-dk52k6-MuiButtonBase-root-MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id(":r25:")).sendKeys("12")
    await driver.findElement(By.css(".MuiButton-fullWidth")).click()
    assert(await driver.switchTo().alert().getText() == "Hardware updated successfully")
    await driver.executeScript("window.scrollTo(0,0)")
  })
})
