// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Admin update user', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Admin update user', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1215, height: 735 })
    await driver.findElement(By.id(":r5:")).sendKeys("admin@locamat.fr")
    await driver.findElement(By.id(":r7:")).sendKeys("Root123@")
    await driver.findElement(By.id(":r5:")).click()
    {
      const element = await driver.findElement(By.id(":r5:"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.id(":r5:"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.id(":r5:"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.id(":r5:")).click()
    await driver.findElement(By.css("form")).click()
    await driver.findElement(By.id(":r7:")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".MuiSvgIcon-fontSizeSmall > path"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiSvgIcon-fontSizeSmall > path")).click()
    await driver.findElement(By.css(".MuiButton-root")).click()
    {
      const element = await driver.findElement(By.css(".material-card:nth-child(2) .MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".material-card:nth-child(1) .MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".MuiButtonBase-root:nth-child(3)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(3)")).click()
    await driver.findElement(By.css(".MuiTableRow-root:nth-child(3) .MuiButtonBase-root:nth-child(1) > .MuiSvgIcon-root")).click()
    await driver.findElement(By.css("p:nth-child(3)")).click()
    await driver.findElement(By.css("p:nth-child(3)")).click()
    {
      const element = await driver.findElement(By.css("p:nth-child(3)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css("p > input")).click()
    await driver.findElement(By.css("p > input")).sendKeys("0000000121")
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(5)")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".MuiButton-root:nth-child(1)")).click()
    await driver.findElement(By.css(".MuiTableRow-root:nth-child(3) .MuiButtonBase-root:nth-child(1) > .MuiSvgIcon-root")).click()
    {
      const element = await driver.findElement(By.css("p:nth-child(3)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css("p > input")).click()
    await driver.findElement(By.css("p > input")).sendKeys("0000000321")
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(5)")).click()
    await driver.findElement(By.css(".MuiTableRow-root:nth-child(1) .MuiButtonBase-root:nth-child(1) > .MuiSvgIcon-root")).click()
    await driver.findElement(By.css(".MuiButton-root:nth-child(1)")).click()
    await driver.close()
  })
})
