// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('1.0 Connexion with classic user', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('1.0 Connexion with classic user', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1215, height: 735 })
    await driver.findElement(By.id(":r5:")).sendKeys("jean@locamat.fr")
    await driver.findElement(By.id(":r7:")).sendKeys("Jean123@")
    await driver.findElement(By.id(":r5:")).click()
    await driver.findElement(By.id(":r7:")).click()
    await driver.findElement(By.css(".MuiButton-root")).click()
    vars["var"] = await driver.executeScript("return document.URL")
    assert(vars["var"].toString() == "http://localhost:5173/home")
  })
})
