// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Home Page', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Home Page', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1215, height: 735 })
    await driver.findElement(By.id(":r5:")).sendKeys("jean@locamat.fr")
    await driver.findElement(By.id(":r7:")).sendKeys("Jean123@")
    await driver.findElement(By.css(".MuiButton-root")).click()
    await driver.findElement(By.css(".material-card:nth-child(1) .MuiPaper-root:nth-child(2) .MuiCardMedia-root")).click()
    await driver.findElement(By.linkText("Home")).click()
    await driver.findElement(By.css(".material-card:nth-child(1) .MuiButtonBase-root")).click()
    await driver.findElement(By.css(".cardHardware:nth-child(2) .imgHardware")).click()
    {
      const element = await driver.findElement(By.linkText("Home"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("Home")).click()
    await driver.close()
  })
})
